apiVersion: apps/v1
kind: Deployment
metadata:
  name: mayank
  labels:
    app: django-blog

spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-blog
  template:
    metadata:
      labels:
        app: django-blog
    spec:
      containers:
      - name: mayank
        image: mayankkamboj1307/docker:1
        ports:
        - containerPort: 8000